spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      database: voting-challenge
      auto-index-creation: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

springdoc:
  default-produces-media-type: application/json

client:
  user:
    url: https://user-info.herokuapp.com/users

vote-session-exchange: vote-exchange
vote-session-dlq-exchange: vote-dlq-exchange